#!/usr/bin/env python3
"""
Python port of build-font-ids.sh
Generates src/fontIds.h by hashing the builtin font header files.
"""

import hashlib
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
FONTS_DIR = os.path.join(SCRIPT_DIR, "..", "builtinFonts")
OUTPUT_FILE = os.path.join(SCRIPT_DIR, "..", "..", "..", "src", "fontIds.h")


def font_id(*filenames):
    """Compute a signed 32-bit font ID from one or more font header files."""
    total = 0
    for fname in filenames:
        path = os.path.join(FONTS_DIR, fname)
        with open(path, "rb") as f:
            digest = hashlib.sha256(f.read()).hexdigest()
        total += int(digest, 16)
    # Same arithmetic as the Ruby version: sum % 2^32 - 2^31
    return total % (2**32) - (2**31)


# --- Font groups (mirrors the .sh script, extended for files present on disk) ---

FONTS = [
    ("NOTOSERIF_12_FONT_ID", [
        "notoserif_12_regular.h",
        "notoserif_12_bold.h",
        "notoserif_12_bolditalic.h",
        "notoserif_12_italic.h",
    ]),
    ("NOTOSERIF_14_FONT_ID", [
        "notoserif_14_regular.h",
        "notoserif_14_bold.h",
        "notoserif_14_bolditalic.h",
        "notoserif_14_italic.h",
    ]),
    ("NOTOSERIF_16_FONT_ID", [
        "notoserif_16_regular.h",
        "notoserif_16_bold.h",
        "notoserif_16_bolditalic.h",
        "notoserif_16_italic.h",
    ]),
    ("NOTOSERIF_18_FONT_ID", [
        "notoserif_18_regular.h",
        "notoserif_18_bold.h",
        "notoserif_18_bolditalic.h",
        "notoserif_18_italic.h",
    ]),
    ("NOTOSANS_12_FONT_ID", [
        "notosans_12_regular.h",
        "notosans_12_bold.h",
        "notosans_12_bolditalic.h",
        "notosans_12_italic.h",
    ]),
    ("NOTOSANS_14_FONT_ID", [
        "notosans_14_regular.h",
        "notosans_14_bold.h",
        "notosans_14_bolditalic.h",
        "notosans_14_italic.h",
    ]),
    ("NOTOSANS_16_FONT_ID", [
        "notosans_16_regular.h",
        "notosans_16_bold.h",
        "notosans_16_bolditalic.h",
        "notosans_16_italic.h",
    ]),
    ("NOTOSANS_10_FONT_ID", [
        "notosans_10_regular.h",
        "notosans_10_bold.h",
        "notosans_10_bolditalic.h",
        "notosans_10_italic.h",
    ]),
    ("UI_10_FONT_ID", [
        "ubuntu_10_regular.h",
        "ubuntu_10_bold.h",
    ]),
    ("UI_12_FONT_ID", [
        "ubuntu_12_regular.h",
        "ubuntu_12_bold.h",
    ]),
    ("SMALL_FONT_ID", [
        "notosans_8_regular.h",
    ]),
]


def main():
    lines = []
    lines.append("// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh (Python port)")
    lines.append("#pragma once")
    lines.append("")

    defines = []
    for macro, files in FONTS:
        # Skip groups where any file is missing
        missing = [f for f in files if not os.path.exists(os.path.join(FONTS_DIR, f))]
        if missing:
            print(f"  [skip] {macro}: missing files: {missing}", file=sys.stderr)
            continue
        fid = font_id(*files)
        lines.append(f"#define {macro} ({fid})")
        defines.append(macro)

    lines.append("")
    lines.append("// Font ID 0 is reserved as the \"not found\" sentinel.")
    lines.append("// Guard against any hash accidentally producing 0.")
    for macro in defines:
        lines.append(f'static_assert({macro} != 0, "Font ID collision with sentinel");')
    lines.append("")

    content = "\n".join(lines)

    with open(OUTPUT_FILE, "w", newline="\r\n") as f:
        f.write(content)

    print(f"Written: {OUTPUT_FILE}", file=sys.stderr)
    print(content)


if __name__ == "__main__":
    main()
