// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define BOOKERLY_12_FONT_ID ()
#define BOOKERLY_14_FONT_ID ()
#define BOOKERLY_16_FONT_ID ()
#define BOOKERLY_18_FONT_ID ()
#define NOTOSANS_12_FONT_ID ()
#define NOTOSANS_14_FONT_ID ()
#define NOTOSANS_16_FONT_ID ()
#define NOTOSANS_10_FONT_ID ()
#define OPENDYSLEXIC_8_FONT_ID ()
#define OPENDYSLEXIC_10_FONT_ID ()
#define OPENDYSLEXIC_12_FONT_ID ()
#define OPENDYSLEXIC_14_FONT_ID ()
#define UI_10_FONT_ID ()
#define UI_12_FONT_ID ()
#define SMALL_FONT_ID ()
