// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh (Python port)
#pragma once

#define NOTOSERIF_12_FONT_ID (-146430884)
#define NOTOSERIF_14_FONT_ID (1897173573)
#define NOTOSERIF_16_FONT_ID (-1070482889)
#define NOTOSERIF_18_FONT_ID (391428969)
#define NOTOSANS_12_FONT_ID (-2066961215)
#define NOTOSANS_14_FONT_ID (-592704164)
#define NOTOSANS_16_FONT_ID (2114224064)
#define NOTOSANS_10_FONT_ID (-809900598)
#define OPENDYSLEXIC_8_FONT_ID (-715871919)
#define OPENDYSLEXIC_10_FONT_ID (609762033)
#define OPENDYSLEXIC_12_FONT_ID (1178148408)
#define OPENDYSLEXIC_14_FONT_ID (1011220402)
#define UI_10_FONT_ID (1675321550)
#define UI_12_FONT_ID (-1596278467)
#define SMALL_FONT_ID (287105211)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(NOTOSERIF_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(OPENDYSLEXIC_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(OPENDYSLEXIC_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(OPENDYSLEXIC_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(OPENDYSLEXIC_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
