// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh (Python port)
#pragma once

#define NOTOSERIF_12_FONT_ID (2001052764)
#define NOTOSERIF_14_FONT_ID (-250310075)
#define NOTOSERIF_16_FONT_ID (1077000759)
#define NOTOSERIF_18_FONT_ID (-1756054679)
#define NOTOSANS_12_FONT_ID (80522433)
#define NOTOSANS_14_FONT_ID (1554779484)
#define NOTOSANS_16_FONT_ID (-33259584)
#define NOTOSANS_10_FONT_ID (1337583050)
#define UI_10_FONT_ID (-15528088)
#define UI_12_FONT_ID (-1583592634)
#define SMALL_FONT_ID (-925263299)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(NOTOSERIF_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
